export enum UserRole {
  ADMIN = 'ADMIN',
  MANAGER = 'MANAGER',
  AGENT = 'AGENT',
  COMPLIANCE = 'COMPLIANCE',
  READ_ONLY = 'READ_ONLY'
}

export enum LeadSource {
  INBOUND_CALL = 'INBOUND_CALL',
  WEB_FORM = 'WEB_FORM',
  TRANSFER = 'TRANSFER',
  LIST = 'LIST',
  REFERRAL = 'REFERRAL',
  OTHER = 'OTHER'
}

export enum LeadStatus {
  NEW = 'NEW',
  CONTACT_ATTEMPTED = 'CONTACT_ATTEMPTED',
  CONTACTED = 'CONTACTED',
  SOA_REQUIRED = 'SOA_REQUIRED',
  SOA_COMPLETED = 'SOA_COMPLETED',
  IN_DISCUSSION = 'IN_DISCUSSION',
  ENROLLED = 'ENROLLED',
  NOT_INTERESTED = 'NOT_INTERESTED',
  DO_NOT_CONTACT = 'DO_NOT_CONTACT'
}

export enum TaskType {
  CALL_BACK = 'CALL_BACK',
  FOLLOW_UP = 'FOLLOW_UP',
  DOCUMENT_REQUEST = 'DOCUMENT_REQUEST',
  COMPLIANCE_REVIEW = 'COMPLIANCE_REVIEW',
  OTHER = 'OTHER'
}

export enum TaskStatus {
  OPEN = 'OPEN',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED'
}

export enum TaskPriority {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH'
}

export enum CallDirection {
  INBOUND = 'INBOUND',
  OUTBOUND = 'OUTBOUND'
}

export enum CallPurpose {
  EDUCATION = 'EDUCATION',
  MARKETING = 'MARKETING',
  ENROLLMENT = 'ENROLLMENT',
  SERVICE = 'SERVICE'
}

export enum CallStatus {
  INITIATED = 'INITIATED',
  RINGING = 'RINGING',
  CONNECTED = 'CONNECTED',
  FAILED = 'FAILED',
  COMPLETED = 'COMPLETED',
  ABANDONED = 'ABANDONED'
}

export enum ComplianceState {
  PRE_CALL_CHECKS_PENDING = 'PRE_CALL_CHECKS_PENDING',
  PRE_CALL_CHECKS_FAILED = 'PRE_CALL_CHECKS_FAILED',
  PRE_CALL_CHECKS_PASSED = 'PRE_CALL_CHECKS_PASSED',
  SOA_REQUIRED = 'SOA_REQUIRED',
  SOA_COMPLETED = 'SOA_COMPLETED',
  DISCLOSURES_PENDING = 'DISCLOSURES_PENDING',
  DISCLOSURES_COMPLETED = 'DISCLOSURES_COMPLETED',
  READY_FOR_ENROLLMENT = 'READY_FOR_ENROLLMENT'
}

export enum EnrollmentStatus {
  SUBMITTED = 'SUBMITTED',
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED'
}

export enum EnrollmentVerificationMethod {
  PHONE = 'PHONE',
  EMAIL = 'EMAIL',
  LETTER = 'LETTER'
}

export enum EnrollmentVerificationOutcome {
  CONFIRMED = 'CONFIRMED',
  NOT_REACHED = 'NOT_REACHED',
  REFUSED = 'REFUSED',
  CANCELLED = 'CANCELLED',
  PENDING = 'PENDING'
}
